retail360_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}" # or a custom role with appropriate permissions
      database: "{{ env_var('SNOWFLAKE_DATABASE') | upper }}" # or your chosen database
      warehouse: "{{ env_var('SNOWFLAKE_WH') }}" # or your chosen warehouse
      schema: "STAGING"                  # default schema
      threads: 4
      client_session_keep_alive: false
